Feature/statistics
acmucsd/diamondhacks-2025 pull request #9
Opened 2024-11-22 02:39 UTC by serrachow

# Info

Closes **[ISSUE NUMBER]**.

[description]

## Changes

- [Fill in here]

# Type of Change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally on Desktop.
- [ ] on the live deployment preview on Desktop.
- [ ] on the live deployment preview on Mobile.
- [ ] I have added new Cypress tests that are passing.

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have followed the style guidelines of this project.
- [x] I have documented any new functions in `/src/lib/*` and commented hard to understand areas
      anywhere else.
- [x] My changes produce no new warnings.

# Screenshots

![image](https://github.com/user-attachments/assets/631b6133-4d13-4238-8f33-1fd6cd6620bc)

![image](https://github.com/user-attachments/assets/2732576c-d128-4582-a06a-d6317ca27f8a)

2024-11-22 03:51 UTC, angela139 requested changes
Overall, it looks really good to me! I left some comments and nits

2024-11-22 03:51 UTC, angela139 commented on src/components/StatsNumbers/style.module.scss
> +    font-size: 1.75em;
Change em to rem since you're not changing the font sizing for a parent container

2024-11-22 03:51 UTC, angela139 commented on src/components/StatsNumbers/style.module.scss
> +    color: vars.$light-blue;
Change color to regular blue per Figma design

2024-11-22 03:51 UTC, angela139 commented on src/sections/Statistics/index.tsx
> +                <Image src="/sliding_diamond.png"
Nit: import the image instead

2024-11-22 03:51 UTC, angela139 commented on src/sections/Statistics/style.module.scss
> +  margin-top: 10px;
Add flex container to main page and then use gap instead to space out the sections

2024-11-22 03:51 UTC, angela139 commented on src/sections/Statistics/style.module.scss
> +    aspect-ratio: 1;
Maybe edit the aspect ratio to match the figma so the diamond guy is the right size

2024-12-10 04:14 UTC, alexzhang1618 commented
Cleaned up the code and updated the mobile layout + the hanging guy

https://github.com/user-attachments/assets/231f3323-0ae8-4da9-a25e-fe427c62460a

2024-12-10 05:11 UTC, SheepTester approved these changes
looks good! the image looks a bit low quality on my screen, maybe export a higher quality version from Figma? (with 2x resolution; or use SVG)

![image](https://github.com/user-attachments/assets/4a4945a2-bb5b-4ee0-ad76-61d5dac362f2)

animating the guy sliding down could potentially be done by exporting the diamond guy as a separate image, then using `position: sticky; top: 0;`. the heister will be constrained to the bounds of its parent element, so that can be used to prevent it from sliding off the rope. but this can/should be done in a separate PR

2024-12-10 05:11 UTC, SheepTester commented on src/components/StatsDescription/index.tsx
> +        <span className={styles.hacks}>Hacks</span> to new heights!
This could potentially be its own component since it's also used in "What is DiamondHacks?" but not important

2024-12-10 05:11 UTC, SheepTester commented on src/components/Footer/index.tsx
> +          <Image src="/assets/acm-logo.png" alt="ACM" width={144} height={144} />
might it be better to import the png file directly? like what is done for `SlidingDiamond`? I think it exports an object with metadata that Next.JS is able to use for certain optimizations

2024-12-10 05:44 UTC, merged